apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextjsss-6563a38c-618f-48c0-ab15-46221fdfac9f-certificate
  namespace: nextjsss-6563a38c-618f-48c0-ab15-46221fdfac9f
spec:
  secretName: nextjsss-6563a38c-618f-48c0-ab15-46221fdfac9f-secret-tls
  commonName: lyna-nextjsss.assessify.org
  dnsNames:
  - lyna-nextjsss.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
